version: '3'

services:
  backend:
    container_name: backend
    build: ./backend
    tty: true
    volumes:
     - ./backend/source:/django
    ports:
     - 8000:8000
    image: backend:django
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - 3333:3306
    environment:
      MYSQL_DATABASE: 'django'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    platform:
      linux/amd64
  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/:/usr/src/app
    command: sh -c 'cd frontend && yarn start'
    ports:
      - 3000:3000
    tty: true
